# Generated by Django 2.2.1 on 2019-05-15 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerinformation',
            name='apartment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apartment.Apartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyerinformation',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
