# Generated by Django 2.2.1 on 2019-05-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_apartment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='image',
        ),
    ]
