# Generated by Django 2.2.1 on 2019-05-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_remove_apartment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='buyerinformation',
            name='month',
            field=models.CharField(max_length=2),
        ),
    ]
