# Generated by Django 2.2.1 on 2019-05-17 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_auto_20190517_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhouse',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openhouse',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openhouse',
            name='time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
