INSERT INTO profile_profile (address, phone, user_id) VALUES('Hrauntunga 69', 8989612, 1);

INSERT INTO profile_profileimage(image, profile_id) VALUES ('https://static1.squarespace.com/static/53a8283de4b00f6c42318d1a/53a828b8e4b057f6687a7837/58b02130db29d65c64131fd9/1487938244007/21+copy.jpg', 1);

INSERT INTO apartment_apartment (address, city, country_id, zip, price, rooms, description, realator_id) VALUES('Kinnargata 3', 'Garðabær', 93, '210', 110000000, 5, 'Flott hús', 1);
INSERT INTO apartment_apartment (address, city, country_id, zip, price, rooms,description, realator_id ) VALUES('Kögursel 20', 'Reykjavík', 93, '109', 57000000, 4, 'Ljótt hús', 1);
INSERT INTO apartment_apartment (address, city, country_id, zip, price, rooms,description, realator_id ) VALUES('5943 New England Woods Dr', 'Burke', 193, '22015', 120000000, 6, 'hús', 2);
INSERT INTO apartment_apartment (address, city, country_id, zip, price, rooms,description, realator_id) VALUES('Skildingarnes 40', 'Reykjavík', 93, '090152', 99000000, 5, 'annað hús', 2);
INSERT INTO apartment_apartment (address, city, country_id, zip, price,rooms, description, realator_id) VALUES('5431 Vista Grande St', 'West Hollywood', 193, '210', 210000000, 7, 'hollywood', 3);

INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://media.treehugger.com/assets/images/2017/12/Villa-S-by-RAU-Architecten-3-1020x610_1.jpg.860x0_q70_crop-scale.jpg',1);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('http://fashionelly.com/images/2016/Modern-Living-Room-Designs-You-Should-Try-5.jpg',1);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://www.bestparticleboardfurniture.com/is/productpic/pb_uk41531964352.jpg',1);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://cdn.mbl.is/frimg/9/38/938714.jpg',1);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://www.icelandairhotels.com/static/gallery/marina-is/icelandair.hotel_.reykjavik.marina.suite_.2floor.jpg',1);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://serefni.is/wp-content/uploads/2015/04/Nordsj%C3%B6-Silfurgr%C3%A1tt-g%C3%B3lf-og-veggir-ON.00.76.jpg',1);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://cdn.mbl.is/frimg/7/77/777881.jpg',2);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://cdn.apartmenttherapy.info/image/fetch/f_auto,q_auto:eco/https://storage.googleapis.com/gen-atmedia/2/2018/01/b3da7335a48eeb71b7c691a5b007621c97fba9cd.jpeg',2);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('http://bryndiseva.is/wp-content/uploads/2016/03/Bedroom_01.jpg?w=575&h=751',2);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://cdn.mbl.is/frimg/1/2/92/1029211.jpg',2);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://m2.mbl.is/jT5HINgbRwv6_Lo7YjGMt_cV9Ys=/730x487/filters:cropcenter(58,56)/frimg/1/11/38/1113841.jpg',2);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://www.stag.is/static/gallery/myndir-arnarborg-13/lg/forstofa.jpg',2);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://www.theplancollection.com/Upload/Plans/SubCategory/090218023227_Country_Plan_1421158_600_400.jpg',3);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://cdn.shopify.com/s/files/1/0017/9496/5570/collections/living_590x.jpeg?v=1526331879',3);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://krom.is/wp-content/uploads/2017/03/f14645be24bb19e3b5399ebd9f888ac1.jpg',3);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://d5hu1uk9q8r1p.cloudfront.net/ormsson.is/skrar/hth-innrettingar/focus-hvid-eksklusivt-k-kken-01-hth.jpg',3);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://images.victorianplumbing.co.uk/images/Cove-Complete-Bathroom-Suite-l.jpg',3);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://www.rumfatalagerinn.is/lisalib/getfile.aspx?itemid=bf11b045-0fe2-11e6-80cf-005056bc4a5e',3);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://cdn.mbl.is/frimg/7/95/795710.jpg',4);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://i.pinimg.com/originals/33/ca/5e/33ca5e3089f9152b3ade900ae8cf9a2d.jpg',4);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://bjargeyogco.files.wordpress.com/2018/08/img_4062.jpg?w=1000',4);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('http://www.lavaconstruction.com/wp-content/uploads/2015/07/kitchen-furniture-2.jpg',4);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('http://fasteignir.visir.is/thumbnail/489x374/inspiration/c11e686f110ea5faf6e9ae79a4daea7d.jpg',4);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://3.bp.blogspot.com/-ZrasauQkcNg/Wlt0HG_t_HI/AAAAAAAASGo/27o6aftjxzYRc4nHoeBrZL5Rcm3fAYLVACLcBGAs/s1600/Sk%25C3%25A4rmavbild%2B2011-10-12%2Bkl.%2B15.07.06.png',4);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('http://www.contemporist.com/wp-content/uploads/2016/05/modern-architecture_280516_01-800x533.jpg',5);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://static.independent.co.uk/s3fs-public/thumbnails/image/2017/08/14/12/88-89.png',5);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://serefni.is/wp-content/uploads/2015/04/Nordsj%C3%B6-Svefnherbergi-steingr%C3%A1tt.jpg',5);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('https://www.hugi.is/media/contentimages/96260.jpg',5);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('http://www.egillarnason.is/wp-content/uploads/2016/03/Bistrot_riv_01r.jpg.1110x500_q75_crop.jpg',5);
INSERT INTO apartment_apartmentimage(image, apartment_id) VALUES ('http://st.houzz.com/simages/1088314_0_8-4279-eclectic-hall.jpg',5);


--- Insert into Countries ---

INSERT INTO apartment_country(country) VALUES ('Afghanistan');
INSERT INTO apartment_country(country) VALUES ('Albania');
INSERT INTO apartment_country(country) VALUES ('Algeria');
INSERT INTO apartment_country(country) VALUES ('American Samoa');
INSERT INTO apartment_country(country) VALUES ('Andorra');
INSERT INTO apartment_country(country) VALUES ('Angola');
INSERT INTO apartment_country(country) VALUES ('Anguilla');
INSERT INTO apartment_country(country) VALUES ('Antarctica');
INSERT INTO apartment_country(country) VALUES ('Antigua and Barbuda');
INSERT INTO apartment_country(country) VALUES ('Argentina');
INSERT INTO apartment_country(country) VALUES ('Armenia');
INSERT INTO apartment_country(country) VALUES ('Aruba');
INSERT INTO apartment_country(country) VALUES ('Australia');
INSERT INTO apartment_country(country) VALUES ('Austria');
INSERT INTO apartment_country(country) VALUES ('Azerbaijan');
INSERT INTO apartment_country(country) VALUES ('Bahamas');
INSERT INTO apartment_country(country) VALUES ('Bahrain');
INSERT INTO apartment_country(country) VALUES ('Bangladesh');
INSERT INTO apartment_country(country) VALUES ('Barbados');
INSERT INTO apartment_country(country) VALUES ('Belarus');
INSERT INTO apartment_country(country) VALUES ('Belgium');
INSERT INTO apartment_country(country) VALUES ('Belize');
INSERT INTO apartment_country(country) VALUES ('Benin');
INSERT INTO apartment_country(country) VALUES ('Bermuda');
INSERT INTO apartment_country(country) VALUES ('Bhutan');
INSERT INTO apartment_country(country) VALUES ('Bolivia');
INSERT INTO apartment_country(country) VALUES ('Bosnia and Herzegovina');
INSERT INTO apartment_country(country) VALUES ('Botswana');
INSERT INTO apartment_country(country) VALUES ('Bouvet Island');
INSERT INTO apartment_country(country) VALUES ('Brazil');
INSERT INTO apartment_country(country) VALUES ('British Indian Ocean Territory');
INSERT INTO apartment_country(country) VALUES ('Brunei Darussalam');
INSERT INTO apartment_country(country) VALUES ('Bulgaria');
INSERT INTO apartment_country(country) VALUES ('Burkina Faso');
INSERT INTO apartment_country(country) VALUES ('Burundi');
INSERT INTO apartment_country(country) VALUES ('Cambodia');
INSERT INTO apartment_country(country) VALUES ('Cameroon');
INSERT INTO apartment_country(country) VALUES ('Canada');
INSERT INTO apartment_country(country) VALUES ('Cape Verde');
INSERT INTO apartment_country(country) VALUES ('Cayman Islands');
INSERT INTO apartment_country(country) VALUES ('Central African Republic');
INSERT INTO apartment_country(country) VALUES ('Chad');
INSERT INTO apartment_country(country) VALUES ('Chile');
INSERT INTO apartment_country(country) VALUES ('China');
INSERT INTO apartment_country(country) VALUES ('Christmas Island');
INSERT INTO apartment_country(country) VALUES ('Cocos (Keeling) Islands');
INSERT INTO apartment_country(country) VALUES ('Colombia');
INSERT INTO apartment_country(country) VALUES ('Comoros');
INSERT INTO apartment_country(country) VALUES ('Congo');
INSERT INTO apartment_country(country) VALUES ('Cook Islands');
INSERT INTO apartment_country(country) VALUES ('Costa Rica');
INSERT INTO apartment_country(country) VALUES ('Croatia (Hrvatska)');
INSERT INTO apartment_country(country) VALUES ('Cuba');
INSERT INTO apartment_country(country) VALUES ('Cyprus');
INSERT INTO apartment_country(country) VALUES ('Czech Republic');
INSERT INTO apartment_country(country) VALUES ('Denmark');
INSERT INTO apartment_country(country) VALUES ('Djibouti');
INSERT INTO apartment_country(country) VALUES ('Dominica');
INSERT INTO apartment_country(country) VALUES ('Dominican Republic');
INSERT INTO apartment_country(country) VALUES ('East Timor');
INSERT INTO apartment_country(country) VALUES ('Ecuador');
INSERT INTO apartment_country(country) VALUES ('Egypt');
INSERT INTO apartment_country(country) VALUES ('El Salvador');
INSERT INTO apartment_country(country) VALUES ('Equatorial Guinea');
INSERT INTO apartment_country(country) VALUES ('Eritrea');
INSERT INTO apartment_country(country) VALUES ('Estonia');
INSERT INTO apartment_country(country) VALUES ('Ethiopia');
INSERT INTO apartment_country(country) VALUES ('Faroe Islands');
INSERT INTO apartment_country(country) VALUES ('Fiji');
INSERT INTO apartment_country(country) VALUES ('Finland');
INSERT INTO apartment_country(country) VALUES ('France');
INSERT INTO apartment_country(country) VALUES ('France, Metropolitan');
INSERT INTO apartment_country(country) VALUES ('French Guiana');
INSERT INTO apartment_country(country) VALUES ('French Polynesia');
INSERT INTO apartment_country(country) VALUES ('Gambia');
INSERT INTO apartment_country(country) VALUES ('Georgia');
INSERT INTO apartment_country(country) VALUES ('Germany');
INSERT INTO apartment_country(country) VALUES ('Ghana');
INSERT INTO apartment_country(country) VALUES ('Gibraltar');
INSERT INTO apartment_country(country) VALUES ('Guernsey');
INSERT INTO apartment_country(country) VALUES ('Greece');
INSERT INTO apartment_country(country) VALUES ('Greenland');
INSERT INTO apartment_country(country) VALUES ('Grenada');
INSERT INTO apartment_country(country) VALUES ('Guadeloupe');
INSERT INTO apartment_country(country) VALUES ('Guam');
INSERT INTO apartment_country(country) VALUES ('Guatemala');
INSERT INTO apartment_country(country) VALUES ('Guinea');
INSERT INTO apartment_country(country) VALUES ('Guyana');
INSERT INTO apartment_country(country) VALUES ('Haiti');
INSERT INTO apartment_country(country) VALUES ('Honduras');
INSERT INTO apartment_country(country) VALUES ('Hong Kong');
INSERT INTO apartment_country(country) VALUES ('Hungary');
INSERT INTO apartment_country(country) VALUES ('Iceland');
INSERT INTO apartment_country(country) VALUES ('India');
INSERT INTO apartment_country(country) VALUES ('Indonesia');
INSERT INTO apartment_country(country) VALUES ('Iran (Islamic Republic of)');
INSERT INTO apartment_country(country) VALUES ('Iraq');
INSERT INTO apartment_country(country) VALUES ('Ireland');
INSERT INTO apartment_country(country) VALUES ('Israel');
INSERT INTO apartment_country(country) VALUES ('Italy');
INSERT INTO apartment_country(country) VALUES ('Ivory Coast');
INSERT INTO apartment_country(country) VALUES ('Jersey');
INSERT INTO apartment_country(country) VALUES ('Jamaica');
INSERT INTO apartment_country(country) VALUES ('Japan');
INSERT INTO apartment_country(country) VALUES ('Jordan');
INSERT INTO apartment_country(country) VALUES ('Kazakhstan');
INSERT INTO apartment_country(country) VALUES ('Kenya');
INSERT INTO apartment_country(country) VALUES ('Kiribati');
INSERT INTO apartment_country(country) VALUES ('Korea, Democratic People''s Republic of');
INSERT INTO apartment_country(country) VALUES ('Korea, Republic of');
INSERT INTO apartment_country(country) VALUES ('Kosovo');
INSERT INTO apartment_country(country) VALUES ('Kuwait');
INSERT INTO apartment_country(country) VALUES ('Kyrgyzstan');
INSERT INTO apartment_country(country) VALUES ('Lao People''s Democratic Republic');
INSERT INTO apartment_country(country) VALUES ('Latvia');
INSERT INTO apartment_country(country) VALUES ('Lebanon');
INSERT INTO apartment_country(country) VALUES ('Lesotho');
INSERT INTO apartment_country(country) VALUES ('Liberia');
INSERT INTO apartment_country(country) VALUES ('Libyan Arab Jamahiriya');
INSERT INTO apartment_country(country) VALUES ('Liechtenstein');
INSERT INTO apartment_country(country) VALUES ('Lithuania');
INSERT INTO apartment_country(country) VALUES ('Luxembourg');
INSERT INTO apartment_country(country) VALUES ('Macau');
INSERT INTO apartment_country(country) VALUES ('Macedonia');
INSERT INTO apartment_country(country) VALUES ('Madagascar');
INSERT INTO apartment_country(country) VALUES ('Malawi');
INSERT INTO apartment_country(country) VALUES ('Malaysia');
INSERT INTO apartment_country(country) VALUES ('Maldives');
INSERT INTO apartment_country(country) VALUES ( 'Mali');
INSERT INTO apartment_country(country) VALUES ( 'Malta');
INSERT INTO apartment_country(country) VALUES ('Marshall Islands');
INSERT INTO apartment_country(country) VALUES ('Martinique');
INSERT INTO apartment_country(country) VALUES ('Mauritania');
INSERT INTO apartment_country(country) VALUES ('Mauritius');
INSERT INTO apartment_country(country) VALUES ('Mayotte');
INSERT INTO apartment_country(country) VALUES ('Mexico');
INSERT INTO apartment_country(country) VALUES ('Micronesia, Federated States of');
INSERT INTO apartment_country(country) VALUES ('Moldova, Republic of');
INSERT INTO apartment_country(country) VALUES ('Monaco');
INSERT INTO apartment_country(country) VALUES ('Mongolia');
INSERT INTO apartment_country(country) VALUES ('Montenegro');
INSERT INTO apartment_country(country) VALUES ('Montserrat');
INSERT INTO apartment_country(country) VALUES ('Morocco');
INSERT INTO apartment_country(country) VALUES ('Mozambique');
INSERT INTO apartment_country(country) VALUES ('Myanmar');
INSERT INTO apartment_country(country) VALUES ('Namibia');
INSERT INTO apartment_country(country) VALUES ('Nauru');
INSERT INTO apartment_country(country) VALUES ('Nepal');
INSERT INTO apartment_country(country) VALUES ('Netherlands');
INSERT INTO apartment_country(country) VALUES ('Netherlands Antilles');
INSERT INTO apartment_country(country) VALUES ('New Caledonia');
INSERT INTO apartment_country(country) VALUES ('New Zealand');
INSERT INTO apartment_country(country) VALUES ('Nicaragua');
INSERT INTO apartment_country(country) VALUES ('Niger');
INSERT INTO apartment_country(country) VALUES ('Nigeria');
INSERT INTO apartment_country(country) VALUES ('Norway');
INSERT INTO apartment_country(country) VALUES ('Oman');
INSERT INTO apartment_country(country) VALUES ('Pakistan');
INSERT INTO apartment_country(country) VALUES ('Palestine');
INSERT INTO apartment_country(country) VALUES ('Panama');
INSERT INTO apartment_country(country) VALUES ('Peru');
INSERT INTO apartment_country(country) VALUES ('Philippines');
INSERT INTO apartment_country(country) VALUES ('Pitcairn');
INSERT INTO apartment_country(country) VALUES ('Poland');
INSERT INTO apartment_country(country) VALUES ('Portugal');
INSERT INTO apartment_country(country) VALUES ('Puerto Rico');
INSERT INTO apartment_country(country) VALUES ('Qatar');
INSERT INTO apartment_country(country) VALUES ('Romania');
INSERT INTO apartment_country(country) VALUES ('Saudi Arabia');
INSERT INTO apartment_country(country) VALUES ('Senegal');
INSERT INTO apartment_country(country) VALUES ('Serbia');
INSERT INTO apartment_country(country) VALUES ('Singapore');
INSERT INTO apartment_country(country) VALUES ('Slovakia');
INSERT INTO apartment_country(country) VALUES ('Slovenia');
INSERT INTO apartment_country(country) VALUES ('South Africa');
INSERT INTO apartment_country(country) VALUES ('South Georgia South Sandwich Islands');
INSERT INTO apartment_country(country) VALUES ('South Sudan');
INSERT INTO apartment_country(country) VALUES ('Spain');
INSERT INTO apartment_country(country) VALUES ('Sri Lanka');
INSERT INTO apartment_country(country) VALUES ('Swaziland');
INSERT INTO apartment_country(country) VALUES ('Sweden');
INSERT INTO apartment_country(country) VALUES ('Switzerland');
INSERT INTO apartment_country(country) VALUES ('Taiwan');
INSERT INTO apartment_country(country) VALUES ('Tajikistan');
INSERT INTO apartment_country(country) VALUES ('Tanzania, United Republic of');
INSERT INTO apartment_country(country) VALUES ('Thailand');
INSERT INTO apartment_country(country) VALUES ('Tunisia');
INSERT INTO apartment_country(country) VALUES ('Turkey');
INSERT INTO apartment_country(country) VALUES ('Uganda');
INSERT INTO apartment_country(country) VALUES ('Ukraine');
INSERT INTO apartment_country(country) VALUES ('United Arab Emirates');
INSERT INTO apartment_country(country) VALUES ('United Kingdom');
INSERT INTO apartment_country(country) VALUES ('United States');
INSERT INTO apartment_country(country) VALUES ('United States minor outlying islands');
INSERT INTO apartment_country(country) VALUES ('Uruguay');
INSERT INTO apartment_country(country) VALUES ('Uzbekistan');
INSERT INTO apartment_country(country) VALUES ('Vanuatu');
INSERT INTO apartment_country(country) VALUES ('Vatican City State');
INSERT INTO apartment_country(country) VALUES ('Venezuela');
INSERT INTO apartment_country(country) VALUES ('Vietnam');
INSERT INTO apartment_country(country) VALUES ('Virgin Islands (British)');
INSERT INTO apartment_country(country) VALUES ('Virgin Islands (U.S.)');
INSERT INTO apartment_country(country) VALUES ('Wallis and Futuna Islands');
INSERT INTO apartment_country(country) VALUES ('Western Sahara');
INSERT INTO apartment_country(country) VALUES ('Yemen');
INSERT INTO apartment_country(country) VALUES ('Zaire');
INSERT INTO apartment_country(country) VALUES ('Zambia');
INSERT INTO apartment_country(country) VALUES ('Zimbabwe');
