# Generated by Django 2.2.1 on 2019-05-15 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=999)),
                ('phone', models.IntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=999)),
                ('email', models.CharField(blank=True, max_length=999)),
                ('image', models.CharField(blank=True, default='https://www.autourdelacom.fr/wp-content/uploads/2018/03/default-user-image.png', max_length=999)),
                ('favorite_apartments', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.Apartment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
