# Generated by Django 2.2.1 on 2019-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='https://www.autourdelacom.fr/wp-content/uploads/2018/03/default-user-image.png', max_length=999),
        ),
    ]
