# Generated by Django 2.2.1 on 2019-05-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_apartments',
        ),
    ]
