# Generated by Django 2.2.1 on 2019-05-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20190514_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(blank=True, default='https://www.autourdelacom.fr/wp-content/uploads/2018/03/default-user-image.png', max_length=999),
        ),
    ]
